<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_celeste@4x.png?raw=true" alt="esquema" />
</div>


<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Estructuras-de-iteración" data-toc-modified-id="Estructuras-de-iteración-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Estructuras de iteración</a></span><ul class="toc-item"><li><span><a href="#for" data-toc-modified-id="for-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>for</a></span></li><li><span><a href="#Bucles-for-con-diccionarios" data-toc-modified-id="Bucles-for-con-diccionarios-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Bucles <code>for</code> con diccionarios</a></span></li></ul></li><li><span><a href="#Métodos-interesantes-para-los-for-loops" data-toc-modified-id="Métodos-interesantes-para-los-for-loops-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Métodos interesantes para los for loops</a></span><ul class="toc-item"><li><span><a href="#range()" data-toc-modified-id="range()-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span><code>range()</code></a></span></li><li><span><a href="#enumerate" data-toc-modified-id="enumerate-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span><code>enumerate</code></a></span></li><li><span><a href="#zip()" data-toc-modified-id="zip()-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span><code>zip()</code></a></span></li></ul></li><li><span><a href="#List-comprehensions" data-toc-modified-id="List-comprehensions-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>List comprehensions</a></span><ul class="toc-item"><li><span><a href="#List-Comprehensions-básicas" data-toc-modified-id="List-Comprehensions-básicas-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span><em>List Comprehensions</em> básicas</a></span></li><li><span><a href="#List-comprehension-con-condición-if" data-toc-modified-id="List-comprehension-con-condición-if-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span><em>List comprehension</em> con condición <code>if</code></a></span></li><li><span><a href="#List-comprehension-con-condición-if...-else" data-toc-modified-id="List-comprehension-con-condición-if...-else-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span><em>List comprehension</em> con condición <code>if</code>... <code>else</code></a></span></li><li><span><a href="#Nested-List-Comprehension" data-toc-modified-id="Nested-List-Comprehension-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span><em>Nested List Comprehension</em></a></span></li></ul></li></ul></div>

# Estructuras de iteración 

## for

En jupyter anterior aprendimos que había tres tipos de estructuras de *control flow*, las cuáles incluían:


- **Estructuras de selección**: Las estructuras de selección, también conocidas como estructuras condicionales, nos permiten tomar decisiones ejecutando diferentes secciones de código dependiendo de una o más condiciones. La más básica y ampliamente usada es la declaración `if`, que bifurca el flujo del código en caminos alternativos según se cumplan o no ciertas condiciones. Su sintaxis básica es:

    ```python
    if condicion:
        # código que se ejecuta si la condición es verdadera
    else:
        # código que se ejecuta si la condición es falsa
    ```

    También es común utilizar `elif`  o `else` para manejar múltiples condiciones mutuamente excluyentes dentro de un solo bloque `if`.

- **Estructuras de iteración**: Estas estructuras nos permiten ejecutar un bloque de código repetidamente. Python proporciona dos bucles principales:

    - `for`: Ideal para iterar sobre una secuencia (como una lista o una cadena de texto) o sobre un rango de números. Su sintaxis básica es: 
    
        ```python
        for elemento in secuencia:
            # acción con elemento
        ```

    - `while`: Ejecuta repetidamente un bloque de código mientras se cumpla una condición. Su sintaxis básica es:
    
        ```python
        while condicion:
            # código que se ejecuta repetidamente
        ```

- **Estructuras de control de funciones**: Python utiliza estructuras adicionales para controlar el flujo de ejecución en funciones, incluyendo el manejo de excepciones y la interrupción o continuación de bucles. Este tipo de estructuras no las veremos en el prework, y las aprenderemos en los primeros días de clase del bootcamp,

    - `try`/`except`: Captura y maneja errores o excepciones que ocurren dentro de un bloque de código.

        ```python
        try:
            # intenta ejecutar código que puede fallar
        except ErrorComoOcurre:
            # maneja la excepción
        ```

    - `break`: Termina un bucle antes de que se haya completado su ciclo normal.
    
    - `continue`: Omite el resto del cuerpo del bucle para una iteración particular y continua con la siguiente.

    - `pass`: Actúa como un relleno o marcador temporal y no tiene ningún efecto en el flujo del programa.


En concreto en el jupyter anterior aprendimos las estructuras de selección y los bucles `while` de las estructuras de iteración. Hoy seguiremos profundizando en estas estructuras de iteración con los bucles `for`. En Python, un bucle `for` se utiliza para iterar sobre una secuencia de elementos, como una lista, una tupla, un diccionario o un set, y realizar una acción en cada uno de ellos. La sintaxis básica de un bucle `for` en Python es la siguiente:

```python
for elemento in secuencia:
    # hacer algo con el elemento
```

Donde: 

- `elemento`: será cada elemento de nuestro iterable. Lo podemos llamar elemento, i, brocoli o como queramos! 

- `secuencia`: será el elemento iterable(lista, tupla, diccionario, set, etc.) sobre el que queremos aplicar el `for`

In [1]:
# creemos una lista donde tengamos 4 strings que correspondan a las 4 herramientas de un perfil que trabaja en el mundo de Data
herramientas = ['Regresión Lineal', 'Power BI', 'Pandas', 'SQL']

print("La lista 'herramientas' contiene:", herramientas)
print("---------------------")

# siguiendo la sintaxis de los bucles for, lo iniciamos usando las palabras reservadas for e in
# 📌 fijaos como en este ejemplo, lo que en el ejemplo de la sintaxis llamamos como "elemento" aquí lo estamos llamando herrramienta 
for herramienta in herramientas:

    # con el for lo que estamos haciendo es acceder a cada uno de los elementos de la lista. Lo que estamos haciendo en las siguientes líneas de código es: 

    # 1. imprimir el elemento al que estamos accediendo de la lista
    print(f"estamos accediendo al elemento {herramienta}")

    # 2. imprimir unas barras para que a la hora de visualizar los resultados del for se vea mejor. Esto no es normal hacerlo, es algo meramente educativo para que se vea más claro. 
    print("...........................")

La lista 'herramientas' contiene: ['Regresión Lineal', 'Power BI', 'Pandas', 'SQL']
---------------------
estamos accediendo al elemento Regresión Lineal
...........................
estamos accediendo al elemento Power BI
...........................
estamos accediendo al elemento Pandas
...........................
estamos accediendo al elemento SQL
...........................


Si recordamos la clase sobre listas, aprendimos que podíamos acceder a los elementos de una lista utilizando la indexación con corchetes. La sintaxis para esto sería:

```python
milista[2]  # Accedemos al elemento que está en la posición 3. Recordemos que la indexación en Python comienza en 0.

milista[-1]  # Accedemos al último elemento de la lista.
```

Pero, ¿qué sucedería si usáramos un bucle `for` junto con la indexación de listas?

In [3]:
# veamos cual es el tercer elemento de nuestra lista y almacenarlo en una variable
herramienta_3 = herramientas[2] # esto ya de por si es un único elemento. En este caso, 'Pandas' y es un string
print("La herramienta que está en tercera posición es:", herramienta_3)
print("Si iteramos por la variable 'herramientas_3' nos devolverá...\n")
print("---------------------")

for letra in herramienta_3:
    print(letra)
    print("................")

La herramienta que está en tercera posición es: Pandas
Si iteramos por la variable 'herramienta_3' nos devolverá...

---------------------
P
................
a
................
n
................
d
................
a
................
s
................


<div style="background-color: #F74646; padding: 10px; border-left: 6px solid #000080; color: black; border-radius: 10px;">

Parece que cada elemento de nuestro *string* es una letra individual. Observamos que el `for` está descomponiendo cada elemento de nuestro iterable.

En el caso de listas, tuplas y sets, cada elemento de nuestra estructura de datos (o iterable) representa un elemento individual dentro de la misma. Para iterar sobre diccionarios, utilizamos un enfoque similar, pero con algunas particularidades que exploraremos más adelante en esta lección.

En el caso de los *strings*, cada elemento corresponde a una letra individual que forma parte del *string*.
</div>



Al igual que en los condicionales (`if ... elif ... else`) o los bucles `while`, los bucles se utilizan para más que simplemente imprimir valores; podemos realizar operaciones con los elementos resultantes de la iteración. En este caso, vamos a iterar sobre una lista de números que definiremos a continuación. Además, crearemos una lista vacía donde agregaremos cada elemento de la lista original, incrementado en 1.

In [4]:
# definimos nuestra lista de números
numeros_lista = [1198, 187, 90, 23, 67]
print("La lista 'numeros_lista' contiene:", numeros_lista)
print("---------------------")

# nos creamos una lista vacía
suma_numeros = []
print("La lista 'suma_numeros':", suma_numeros)
print("---------------------\n")

# iniciamos nuestro bucle for iterando por nuestra lista de numeros. Donde numero será cada unos de números que tenemos en la lista. Primero será 1198, luego 187, luego 90, luego 23 y por último 67
for numero in numeros_lista :

    # printemos el número al que estamos accediendo
    print(f"el número al que estamos accediendo es {numero}")

    # al elemento al que estamos accediendo le sumamos uno y lo almacenamos en una variable
    suma = numero + 1

    # añadimos el nuevo número a nuestra lista vacía 'suma_numeros'
    suma_numeros.append(suma)

    # a medida que vamos avanzando en la iteración vamos printeando los resultados de la lista 'suma_numeros'
    print(suma_numeros)
    print("............................")

La lista 'numeros_lista' contiene: [1198, 187, 90, 23, 67]
---------------------
La lista 'suma_numeros': []
---------------------

el número al que estamos accediendo es 1198
[1199]
............................
el número al que estamos accediendo es 187
[1199, 188]
............................
el número al que estamos accediendo es 90
[1199, 188, 91]
............................
el número al que estamos accediendo es 23
[1199, 188, 91, 24]
............................
el número al que estamos accediendo es 67
[1199, 188, 91, 24, 68]
............................


<div style="background-color: #F74646; padding: 10px; border-left: 6px solid #000080; color: black; border-radius: 10px;">

**Entendamos lo que está pasando**

Analicemos los resultados de todos esos *prints* que nos ha devuelto el bucle `for`. Nuestra lista original era la siguiente:

```python
numeros_lista = [1198, 187, 90, 23, 67]
```

- En primer lugar, el *print* muestra el elemento al que estamos accediendo en la iteración, en este caso, el número **1198**. Luego, se lleva a cabo una serie de operaciones, en particular, la suma de dicho elemento más 1. Posteriormente, este resultado se agrega a nuestra lista vacía, y finalmente se imprime la lista resultante. En esta primera iteración, la lista solo contiene un elemento, que es el resultado de sumar `1198 + 1`.

- Al completar la primera iteración, el bucle `for` regresa al principio, esta vez accediendo al segundo elemento, que es el número **187**. Luego, se realiza la suma y se agrega a la lista. Observamos que, al imprimir nuevamente la lista `suma_numeros`, ahora contiene dos elementos: el que se añadió en la iteración anterior y el resultado de sumar `187 + 1`.

- Este proceso se repite para cada elemento de nuestra lista, y el código se detiene al llegar al último elemento.

Observamos que:

- Ambas listas tienen el mismo número de elementos.

- La lista `suma_numeros` contiene los mismos elementos que la lista original, pero a cada uno se le ha sumado 1.
</div>


Vamos a explorar más ejemplos con el bucle `for` para familiarizarnos con su funcionamiento. En esta ocasión, usaremos la lista de herramientas definida al inicio de la lección y queremos imprimir cada una de ellas en mayúscula. Además, deseamos crear una lista que contenga las herramientas en mayúsculas.

In [5]:
# lo primero que hacemos es recordar cual era nuestra lista de herramientas
print("Las herramientas que tenemos en nuestra lista son:", herramientas)
print("-----------------------------------------")

# en segundo lugar creamos una lista vacía donde almancenaremos las herramientas de la lista anterior en mayúscula
herramientas_mayusculas = []
print("El contenido de la lista 'herramientas_mayusculas' contiene:", herramientas_mayusculas)
print("-----------------------------------------")

# iniciamos el for
for elemento in herramientas:
    # sacamos por pantalla la herramienta por la que estamos interando
    print(f"Estamos interando por la herramienta {elemento}")

    # si recordamos antes, nos creamos una variable donde sumamos un valor a nuestro iterable. Este paso lo podemos obviar y añadirlo directamente a la lista, como vamos a hacer en este caso. 
    herramientas_mayusculas.append(elemento.upper())


print("------------------------------")
print("El contenido de la lista 'herramientas_mayusculas' DESPUÉS DEL BUCLE FOR contiene:", herramientas_mayusculas)

print("Y voilá! Ya tenemos una lista nueva con todas las herramientas en mayúsculas 🎊. ")


Las herramientas que tenemos en nuestra lista son: ['Regresión Lineal', 'Power BI', 'Pandas', 'SQL']
-----------------------------------------
El contenido de la lista 'herramientas_mayusculas' contiene: []
-----------------------------------------
Estamos interando por la herramienta Regresión Lineal
Estamos interando por la herramienta Power BI
Estamos interando por la herramienta Pandas
Estamos interando por la herramienta SQL
------------------------------
El contenido de la lista 'herramientas_mayusculas' DESPUÉS DEL BUCLE FOR contiene: ['REGRESIÓN LINEAL', 'POWER BI', 'PANDAS', 'SQL']
Y voilá! Ya tenemos una lista nueva con todas las herramientas en mayúsculas 🎊. 


Incluso podemos dirigir los resultados a listas diferentes. Supongamos que ahora queremos dividir nuestras herramientas según su longitud, es decir, el número de letras que tiene cada una. De este modo, terminaremos con dos listas: una con las herramientas de longitud menor o igual a 6 y otra con las herramientas de longitud mayor a 6.

In [6]:
# nos creamos dos listas, una de ciudades_pequeñas y otra de ciudades_grandes
herramientas_pequeñas = []
herramientas_grandes = []

print("El contenido de la lista 'herramientas_pequeñas' contiene:", herramientas_pequeñas)
print("-----------------------------------------")
print("El contenido de la lista 'herramientas_grandes' contiene:", herramientas_grandes)
print("-----------------------------------------")

# iniciamos nuestro for para iterar por la lista de herramientas y acceder a cada una de ellas: 
for elemento in herramientas:

    # como estamos viendo dentro de un for podemos hacer lo que se nos ocurra. En este vamos a incluir condicionales. 

    # si la longitud de la herramienta a la que estamos accediendo es menor o igual a 6 lo añadiremos a la lista de herramientas pequeñas. En este caso, llamamos "elemento" a cada uno de los elementos de la lista ciudades pero recordad que lo podemos llamar de cualquier forma
    if len(elemento) <= 6:
        herramientas_pequeñas.append(elemento)

    # en caso de que no se cumpla la condición definida previamente, lo añadiremos a la lista de herramientas grandes
    else:
        herramientas_grandes.append(elemento)
# veamos ahora como han quedado nuestras listas

print("Las herramientas pequeñas son: ", herramientas_pequeñas) # tendremos las herramientas que tengan menos de 6 caracteres
print("Las herramientas grandes son: ", herramientas_grandes) # tendremos las herramientas que tengan más de 6 caracteres

El contenido de la lista 'herramientas_pequeñas' contiene: []
-----------------------------------------
El contenido de la lista 'herramientas_grandes' contiene: []
-----------------------------------------
Las herramientas pequeñas son:  ['Pandas', 'SQL']
Las herramientas grandes son:  ['Regresión Lineal', 'Power BI']


## Bucles `for` con diccionarios

Como ya dijimos al inicio, podemos iterar por diccionarios, pero con algunas peculiaridades. A diferencia de las listas, tuplas y sets, donde cada elemento es iterable, en los diccionarios, la iteración se realiza sobre las claves por defecto. La sintaxis básica de un bucle `for` con diccionarios es la siguiente:

```python
for key in dictionary:
    # hacer algo con la clave o el valor
```

Aquí, `key` representa cada clave del diccionario. Sin embargo, si queremos iterar sobre los valores o ambos, debemos usar métodos especiales como `.items()`, `.keys()` o `.values()`. Por ejemplo:

```python
for key, value in dictionary.items():
    # hacer algo con la clave y el valor
```

Este enfoque nos permite acceder tanto a las claves como a los valores asociados en cada iteración. Además, podemos realizar operaciones o ejecutar lógica en función de las claves o los valores durante la iteración.

In [7]:
# lo primero que vamos a hacer es definir un diccionario:

diccionario_compra = {'Brocoli': 2.45, 
       'Chorizo': 45,
       'Zanahoria': 7, 
       'Arroz': 1.2, 
       'Pan': 0.95}

print("El diccionario 'diccionario_compra' contiene", diccionario_compra)
print("-------------------------------")

# que pasaría si usamos un for para iterar por el diccionario? 
for i in diccionario_compra: # fijaos como ahora al iterable lo hemos llamado "i"
    print(i)
    
print("Vale... parece que si iteramos como hemos aprendido hasta ahora solo accedemos a las *keys* de nuestro diccionario. Pero... 🤔 ¿Qué pasaría si quisieramos acceder a los *values*? Recordáis el método `.values()` de los diccionarios?")

El diccionario 'diccionario_compra' contiene {'Brocoli': 2.45, 'Chorizo': 45, 'Zanahoria': 7, 'Arroz': 1.2, 'Pan': 0.95}
-------------------------------
Brocoli
Chorizo
Zanahoria
Arroz
Pan
Vale... parece que si iteramos como hemos aprendido hasta ahora solo accedemos a las *keys* de nuestro diccionario. Pero... 🤔 ¿Qué pasaría si quisieramos acceder a los *values*? Recordáis el método `.values()` de los diccionarios?


In [8]:
# veamos que era los que nos devolvía este método
print("El método '.values()' de los diccionarios nos devuelve los valores de nuestro diccionario, en este caso son:", diccionario_compra.values())
print("-------------------------\n")
#Genial!!! Hemos conseguido acceder a los valores, en este momento la lógica nos podría decir podríamos iterar por esos values! Veamos que pasa!! 
for i in diccionario_compra.values():
    print(i)
    print("........")

El método '.values()' de los diccionarios nos devuelve los valores de nuestro diccionario, en este caso son: dict_values([2.45, 45, 7, 1.2, 0.95])
-------------------------

2.45
........
45
........
7
........
1.2
........
0.95
........


¡Fantástico! Hemos logrado acceder tanto a las claves como a los valores de nuestro diccionario. Pero ahora, ¿qué pasa si queremos acceder a las claves y valores del diccionario simultáneamente? Aquí es donde entra en juego el método `.items()` de los diccionarios. Recordemos qué nos devuelve este método:

```python
for key, value in dictionary.items():
    # hacer algo con la clave y el valor
```

En este caso, `key` representa cada clave del diccionario y `value` representa el valor asociado a esa clave. Al utilizar `.items()`, podemos acceder a ambas partes de cada par clave-valor en cada iteración del bucle `for`. Esto facilita el procesamiento de los datos del diccionario al permitirnos trabajar con ambos componentes simultáneamente. ¡Es como tener acceso completo a toda la información contenida en el diccionario en cada iteración!

Este enfoque es especialmente útil cuando necesitamos realizar operaciones o ejecutar lógica que depende tanto de las claves como de los valores del diccionario. Además, al igual que con otros bucles `for`, podemos realizar cualquier acción deseada dentro del bucle, aprovechando al máximo la versatilidad de Python en el manejo de datos.

In [9]:
print("El método '.items()' de los diccionarios nos devuelve una lista de tuplas con las claves y los valores de nuestro diccionario, en este caso son:", diccionario_compra.items())
print("-------------------------\n")

# iteremos ahora con el método .items(), para el cual deberemos generar dos iterables (key, value)
for key, value in diccionario_compra.items():
    print(key, "---->", value)

El método '.items()' de los diccionarios nos devuelve una lista de tuplas con las claves y los valores de nuestro diccionario, en este caso son: dict_items([('Brocoli', 2.45), ('Chorizo', 45), ('Zanahoria', 7), ('Arroz', 1.2), ('Pan', 0.95)])
-------------------------

Brocoli ----> 2.45
Chorizo ----> 45
Zanahoria ----> 7
Arroz ----> 1.2
Pan ----> 0.95


<div style="background-color: #FFBB33; padding: 10px; border-left: 6px solid #000080; color: black; border-radius: 10px;">

**Analicemos lo que ha ocurrido:**

1. En nuestro bucle <u>for</u>, hemos utilizado dos variables: <u>keys</u> y <u>values</u>. Las hemos nombrado así para que sea más comprensible, pero podríamos haber usado cualquier otro nombre.

2. Utilizamos el método <u>.items()</u> en nuestro diccionario para obtener un objeto de tipo <u>dict_items</u>, que nos proporciona acceso a todas las claves y valores del diccionario simultáneamente.

3. Utilizamos un <u>print</u> dentro del bucle <u>for</u> para mostrar tanto las claves como los valores de nuestro diccionario en cada iteración.

Este enfoque nos permite trabajar eficientemente con las claves y los valores del diccionario al mismo tiempo, lo que facilita el procesamiento de datos y la ejecución de cualquier lógica que dependa de ambos componentes del diccionario. La flexibilidad de Python nos permite adaptar el nombre de las variables y aprovechar al máximo las funcionalidades proporcionadas por los diccionarios.
</div>

In [10]:
# ojo! Si no le añadimos el .items() nos dara error si le pasamos dos itereables en el for   
for key,value in diccionario_compra:
    print(key,value)


ValueError: too many values to unpack (expected 2)

El error `ValueError: too many values to unpack (expected 2)` indica que hemos intentado iterar sobre dos elementos, pero solo tenemos uno, que por defecto en los diccionarios son las *keys*.

Al igual que en los ejemplos anteriores con listas, los bucles `for` con diccionarios nos permiten realizar operaciones más allá de imprimir. Imaginemos que estamos de compras, pero nos hemos olvidado la cartera en casa y solo tenemos dos euros. En esta situación, solo podremos comprar productos que estén por debajo de este precio. ¿Cómo seleccionaríamos esos productos usando Python?

In [11]:
print("El diccionario 'diccionario_compra' contiene", diccionario_compra)
print("-------------------------------")

print("Recordemos que si queremos saber lo que cuesta el brocoli deberemos usar la siguiente sintaxis diccionario_compra[UNA_CALVE], lo cual nos devovlerá el valor de la clave especificada entre corchetes, en este caso sacaremos el precio del brocoli", diccionario_compra["Brocoli"])
print("-------------------------------")


# lo primero que hacemos es crearnos una lista donde almacenaremos los resultados, es decir, los productos que cuesten menos de dos euros
dos_euros = []
print("La lista de 'dos_euros' contiene:", dos_euros)
print("-------------------------------")


# empezamos a iterar por nuestro diccionario de la lista de la compra:
for k, v in diccionario_compra.items():

    # lo siguiente que haremos será buscar aquellas keys, para las cuales sus values sean menores de dos. 

    # usando la sintaxis que ya conocemos para acceder a elementos de un diccionario, que recordamos un par de celdas arriba, podemos acceder a cada una de las keys y values de nuestro diccionario.
    # de esta forma, lo que en nuestro ejemplo de arriba era "Brocoli", dentro del for correspondera a "k". 
    if diccionario_compra[k] < 2: 

        # en caso de que la condición se cumpla, añadiremos la key a nuestra lista dos_euros
        dos_euros.append(k) 
        
print("La lista de 'dos_euros' DESPUÉS DEL BUCLE FOR contiene:", dos_euros)
print("-------------------------------")


El diccionario 'diccionario_compra' contiene {'Brocoli': 2.45, 'Chorizo': 45, 'Zanahoria': 7, 'Arroz': 1.2, 'Pan': 0.95}
-------------------------------
Recordemos que si queremos saber lo que cuesta el brocoli deberemos usar la siguiente sintaxis diccionario_compra[UNA_CALVE], lo cual nos devovlerá el valor de la clave especificada entre corchetes, en este caso sacaremos el precio del brocoli 2.45
-------------------------------
La lista de 'dos_euros' contiene: []
-------------------------------
La lista de 'dos_euros' DESPUÉS DEL BUCLE FOR contiene: ['Arroz', 'Pan']
-------------------------------


# Métodos interesantes para los for loops

## `range()`

El método `range` es una función que genera una secuencia de números enteros. Es una herramienta esencial para la iteración eficiente en Python, especialmente en bucles `for` y la creación de listas numéricas.

La sintaxis completa del método `range` es la siguiente:

```python
range(inicio, fin, paso)
```

Donde:

- `inicio` (opcional): Representa el primer número de la secuencia (inclusive). Por defecto, su valor es 0.
  
- `fin`: Indica el último número de la secuencia (exclusivo). Esto significa que la secuencia finaliza en `fin-1`.
  
- `paso` (opcional): Es el incremento utilizado para generar los números de la secuencia. Por omisión, su valor es 1.

Una de las características más importantes de `range` es su capacidad para generar secuencias de números de manera eficiente, sin almacenar cada número individualmente en la memoria. Esto hace que sea ideal para bucles `for` donde necesitemos iterar sobre un rango de valores o crear listas numéricas extensas.

Además, `range` es versátil y se puede personalizar fácilmente para adaptarse a diversas necesidades. Por ejemplo, podemos especificar el incremento para generar secuencias con patrones específicos, como números pares o impares.

In [14]:
# Utilizamos el método range para generar números del 0 al 6 (inclusive).
# Como mencionamos previamente, para llegar hasta el 6, en el rango debemos especificar el inicio como 0 y el límite como 6 + 1.
numeros = range(0, 7)
print("Los numeros generados por el 'range' son:", numeros)
print("------------------------------")
# Ups... parece que esto no nos devuelve una lista como tal. Pero... ¿podremos iterar por ese elemento? Veámoslo con un ejemplo: 


# Iniciamos un bucle for, utilizando el método range como iterable.
for x in range(7):
    # Imprimimos cada elemento del objeto range.
    print(x)


Los numeros generados por el 'range' son: range(0, 7)
------------------------------
0
1
2
3
4
5
6


In [16]:
# podemos hacer otro ejemplo de range, empezando en el número 3 y termiando en el 10. 
# Fijate como ahora no hemos almacenado el 'range()' en una variable, sino que lo pusimos directamente en el for

for numero in range(3, 11):
    print(numero)

3
4
5
6
7
8
9
10


Si nos fijamos nuestro *range* ha empezado en el 3  y terminado en el 10, nos ha generado números consecutivos de 3 a 10. Como hemos visto, en el `range()` podemos pasar un tercer parámetro. Este parámetro corresponde con los *steps* o saltos que queremos en nuestra secuencia de números. Veamos algunos ejemplos para entender esto mejor:  

In [17]:
# si queremos que se nos genere un secuencia de números del 0 al 10, con saltos de 2 podríamos hacer lo siguiente:
for x in range(0,10,2):
    print(x)

0
2
4
6
8


## `enumerate`

Permite recorrer un iterable (como una lista, diccionario, tupla, set, string) y obtener tanto el índice como el valor del elemento en cada iteración. Esto es particularmente útil cuando necesitamos acceder a la posición de los elementos durante un bucle, lo cual no es posible directamente con un simple bucle `for`.

La sintaxis básica:

```python
enumerate(iterable, start=0)
```

- `iterable`: El objeto que se va a recorrer (por ejemplo, una lista, una cadena, un conjunto, etc.).

- `start`: El valor inicial del índice (opcional, por defecto es 0).

**Las buenas prácticas a la hora de usar el `enumerate` son: 

- **Legibilidad**: Debemos utilizar `enumerate` para mejorar la legibilidad del código en lugar de manejar manualmente los índices.

- **Uso Adecuado del Índice**: Debemos asegurarnos de que los índices devueltos por `enumerate` se utilicen correctamente, especialmente si se modifica el iterable durante la iteración.


In [2]:
# definimos una lista por la que iteraremos
frutas = ["manzana", "banana", "cereza"]

# iniciamos el bucle for, fijaos como ahora, al igual que en los diccionarios, el primero corresponde al índice y el segundo al elemento por el que estamos iterando
for indice, valor in enumerate(frutas):

    # mostramos en pantalla el índice y el valor
    print(f"Índice: {indice}, Valor: {valor}")

Índice: 0, Valor: manzana
Índice: 1, Valor: banana
Índice: 2, Valor: cereza


In [4]:
# vamos a especificar que no queremos que empiece por el índice 0, sino por el 1 usando el parámetro start
for indice, valor in enumerate(frutas, start=1):
    
    # mostramos en pantalla el índice y el valor
    print(f"Índice: {indice}, Valor: {valor}")

Índice: 1, Valor: manzana
Índice: 2, Valor: banana
Índice: 3, Valor: cereza


## `zip()`

Permite combinar dos o más iterables (como listas, tuplas, etc.) en un solo iterable de tuplas. Cada tupla contiene elementos que ocupan la misma posición en los iterables originales. Esta función es útil cuando necesitas iterar sobre múltiples colecciones simultáneamente.

La sintaxis básica es:

```python
zip(iterable1, iterable2, ...)
```

- `iterable1, iterable2, ...`: Los iterables que se van a combinar.



**Las buenas prácticas son:**

- **Mismos tamaños de iterables**: Debemos asegurarnos de que los iterables tengan la misma longitud para evitar pérdida de datos, ya que `zip` detiene la iteración en el final del iterable más corto.

- **Desempaquetado claro**: Debemos utilizar nombres de variables claros al desempaquetar las tuplas de `zip` para mantener la legibilidad del código.


In [8]:
# veamos un ejemplo básico utilizando dos listas
nombres = ["Ana", "Carlos", "Elena"]
edades = [28, 34, 29]

# generamos la variable resultado del zip
combinados = zip(nombres, edades)

# recordad que el zip nos devuelve un objeto de Python
print(f"El resultado del zip es: {combinados}")

# si quisieramos ver lo que genera en zip, lo podríamos convertir a lista.  Fijaos como crea una lista de tuplas!
print(f"El resultado del zip convertido a lista es: {list(combinados)}")

# iteramos por el objeto del zip, accediendo a cada elemento de la tupla
for nombre, edad in zip(nombres, edades):
    print(f"{nombre} tiene {edad} años")

# En este caso estamos combinando los elementos de las listas `nombres` y `edades` en tuplas, y 
# luego iteramos sobre estas tuplas.

El resultado del zip es: <zip object at 0x1114db2c0>
El resultado del zip convertido a lista es: [('Ana', 28), ('Carlos', 34), ('Elena', 29)]
Ana tiene 28 años
Carlos tiene 34 años
Elena tiene 29 años


# List comprehensions

Las `list comprehensions` son una forma concisa y poderosa de crear listas. Permiten generar listas de manera eficiente a partir de iterables como listas, tuplas, o rangos, aplicando transformaciones o filtros a cada elemento en un solo paso. Esto significa que podemos crear y modificar listas de forma rápida y legible en una sola línea de código.

Son útiles en situaciones donde necesitamos construir listas basadas en alguna lógica o cálculo aplicado a elementos existentes. Algunos casos de uso comunes incluyen:

1. **Transformación de datos:** Podemos utilizar *list comprehensions* para aplicar una operación a cada elemento de una lista y construir una nueva lista con los resultados. Por ejemplo, podemos convertir una lista de números en una lista de sus cuadrados o en una lista de cadenas formateadas.

2. **Filtrado de datos:** Podemos utilizar *list comprehensions* para filtrar elementos de una lista que cumplan cierta condición. Esto nos permite crear una sublista que contenga solo los elementos que satisfacen el criterio especificado.

3. **Construcción de listas:** Las *list comprehensions* son útiles cuando queremos construir una lista de manera dinámica, ya sea basada en una serie de valores predefinidos o en una secuencia generada por un bucle.

Las *list comprehensions* son especialmente útiles cuando necesitamos escribir código de manera concisa y legible, evitando la necesidad de escribir bucles `for` tradicionales. Ayudan a reducir la cantidad de código y a mejorar la claridad y la mantenibilidad del código, lo que las convierte en una herramienta poderosa en el arsenal de cualquier programador de Python.


La ventaja de utilizarlas: 

- Son relativamente más rápidas que los bucles for.

- La sintaxis de las comprensiones de lista es más fácil de leer y entender.

> Podríamos decir que las *list comprehension* son una forma de crear listas de una manera elegante y simplificada (en una línea de código). 


**Los tipos de list comprehension que tenemos son:**

- **List Comprehensions Básicas:** Este tipo aplica una expresión a cada elemento del iterable sin filtrar ninguno. La sintaxis es:

   ```python
   nueva_lista = [expresion for elemento in iterable]
   ```

   En este caso, `nueva_lista` contendrá el resultado de aplicar la expresión a cada elemento del iterable, sin aplicar ninguna condición de filtrado. Esta forma es útil cuando se desea aplicar una operación a todos los elementos del iterable sin necesidad de filtrarlos.

- **List Comprehensions con Condición `if`:** Se utiliza para crear una nueva lista aplicando una expresión a cada elemento de un iterable y filtrando los elementos según una condición opcional. La sintaxis básica es la siguiente:

   ```python
   nueva_lista = [expresion for elemento in iterable if condicion]
   ```

   Donde:
   - `expresion` es la operación que se aplicará a cada elemento.

   - `elemento` es una variable que representa cada elemento del iterable.

   - `iterable` es la colección de elementos sobre la que se iterará.

   - `condicion` es una condición opcional que filtra los elementos.

- **List Comprehensions con Condición `if` y `else`:** Se utilizan para crear una nueva lista aplicando una expresión a cada elemento de un iterable y aplicando una operación específica según una condición. La sintaxis básica es la siguiente:

   ```python
   nueva_lista = [expresion_true if condicion else expresion_false for elemento in iterable]
   ```

   Donde:
   - `expresion_true` es la operación que se aplicará a cada elemento si la condición es verdadera.

   - `expresion_false` es la operación que se aplicará a cada elemento si la condición es falsa.

   - `condicion` es una condición que determina qué expresión se aplicará a cada elemento.

   - `elemento` es una variable que representa cada elemento del iterable.
   
   - `iterable` es la colección de elementos sobre la que se iterará.


- **Nested List Comprehensions:** Estas list comprehensions permiten crear listas de listas, es decir, listas anidadas. Se utilizan cuando queremos aplicar una expresión a cada elemento de una lista que está dentro de otra lista. La sintaxis es similar a las list comprehensions básicas, pero se anidan dentro de otra lista comprehension. Por ejemplo:

   ```python
   matriz = [expresion for elemento in fila for fila in matriz_original]
   ```

   Donde:
   - `expresion` es la operación que se aplicará a cada elemento de la fila.

   - `elemento` es una variable que representa cada elemento de la fila.

   - `fila` es una lista dentro de `matriz_original`.

   - `matriz_original` es una lista de listas.

## *List Comprehensions* básicas

La sintaxis que seguiremos en este tipo de aproximaciones es: 

![lista](https://github.com/Hack-io-Data/Imagenes/blob/main/02-Imagenes/Python_b%C3%A1sico/list_comprehension_basica.png?raw=true)

Veamos un ejercicio sencillo para entender como funciona de una forma práctica. Imaginemos que tenemos una lista de números del 0 al 50000000 (la crearemos con un `range` como hemos aprendido), y queremos crearnos una lista nueva con los mismo números pero en este caso querremos los números elevados al cuadrado. 

En este caso vamos a añadir al inicio de la celda `%%time`. Este comando es una *magic command* específica de Jupyter Notebook que se utiliza para medir el tiempo de ejecución de una celda de código. Cuando se coloca al principio de una celda de código, nos permite medir el tiempo que tarda en ejecutarse todo el contenido de esa celda.

Al ejecutar una celda con `%%time`, Jupyter Notebook mostrará dos tipos de tiempo:

- **Tiempo de CPU**: Es el tiempo total de la CPU utilizado para ejecutar el código en la celda.
  
- **Tiempo de pared (Wall time)**: Es el tiempo total que transcurre desde que se inicia la ejecución de la celda hasta que finaliza, incluyendo cualquier tiempo de espera o bloqueo.

Estos tiempos son útiles para evaluar el rendimiento y la eficiencia de un código, especialmente cuando se están realizando optimizaciones o comparaciones entre diferentes enfoques de implementación.

In [20]:
%%time

# con un for loop como hemos aprendido hasta ahora 
# creamos una lista vacía donde iremos añadiendo cada nuevo valor
cuadrado = []
print("La lista con los cuadrados de los números contiene:", cuadrado)
print("--------------------------------")

# iniciamos nuestro for sobre la lista de números que crearemos con un for: 
for num in range(50000000):

    # apendeamos a la lista nueva "cuadrado" los valores por los que vamos iterando elevados al cuadrado
    cuadrado.append(num ** 2)

print("La lista DESPUÉS DEL BUCLE FOR contiene, notad como solo hemos mostrado los primeros elementos para simplificar el output:", cuadrado[:20])

La lista con los cuadrados de los números contiene: []
--------------------------------
La lista DESPUÉS DEL BUCLE FOR contiene, notad como solo hemos mostrado los primeros elementos para simplificar el output: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
CPU times: user 1.42 s, sys: 111 ms, total: 1.53 s
Wall time: 1.54 s


In [21]:
%%time
# con una list comprehension
cuadrado2 = [num ** 2 for num in range(50000000)]

# veamos el contenido de la lista cuadrado2
print("La lista contiene, notad como solo hemos mostrado los primeros elementos para simplificar el output:", cuadrado2[:20])

La lista contiene, notad como solo hemos mostrado los primeros elementos para simplificar el output: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]
CPU times: user 900 ms, sys: 128 ms, total: 1.03 s
Wall time: 1.07 s


<div style="background-color: #FFBB33; padding: 10px; border-left: 6px solid #000080; color: black; border-radius: 10px;">

**Interpretemos lo que ha pasado** 

Si observamos los tiempos de ejecución de las dos celdas anteriores, notamos que, aunque no en gran medida, la *list comprehension* se ejecutó más rápidamente. Ahora, analicemos el código de la *list comprehension* para comprenderlo mejor:

- Definimos una variable llamada `cuadrado2`, donde se almacenarán los resultados del *for loop*.

- Para crear una *list comprehension*, utilizamos corchetes (`[]`) al principio y al final.

- Dentro de los corchetes, especificamos `num ** 2`, que representa lo que queremos agregar en nuestra nueva lista, equivalente a la segunda línea de nuestro *for* original. Esto indica qué acción queremos realizar con cada elemento de nuestra lista original.

- Luego, utilizamos `for num in range(5000000)` para iniciar nuestro *for loop*.

Hemos desglosado cada una de las partes de la *list comprehension*. Ahora, exploremos algunos ejemplos adicionales.
</div>




Imaginemos ahora que tenemos una lista de palabras y vamos a querer crearnos otra con las longitudes de cada una de ellas. 

In [30]:
%%time
# lo primero que hacemos es definir la lista de palabras

palabras = ["hackio", "python", "data analysts", "sql", "programadoras"]
print("La lista 'palabras' contiene:", palabras)
print("----------------------")

# hagámoslo con un for loop tradicional

# primero definimos la lista vacía donde apendearemos las longitudes de las palabras
palabras_len = []
print("La lista con las longitudes de cada palabra antes del bucle contiene:", palabras_len)

# inicimos nuestro for
for palabra in palabras:

    # apendeamnos en la lista vacía las longitudes de cada una de las palabras de nuestra lista
    palabras_len.append(len(palabra))
print("----------------------")
print("La lista con las longitudes de cada palabra DESPUÉS del bucle contiene:", palabras_len)


La lista 'palabras' contiene: ['hackio', 'python', 'data analysts', 'sql', 'programadoras']
----------------------
La lista con las longitudes de cada palabra antes del bucle contiene: []
----------------------
La lista con las longitudes de cada palabra DESPUÉS del bucle contiene: [6, 6, 13, 3, 13]
CPU times: user 93 µs, sys: 9 µs, total: 102 µs
Wall time: 98.2 µs


In [29]:
%%time
# hagamoslo ahora con una list comprehension
palabras_len2 = [len(pal) for pal in palabras]

# vemos el contenido de palabras_len2
print("La lista con las longitudes de cada palabra DESPUÉS del bucle contiene", palabras_len2)

La lista con las longitudes de cada palabra DESPUÉS del bucle contiene [6, 6, 13, 3, 13]
CPU times: user 35 µs, sys: 5 µs, total: 40 µs
Wall time: 41 µs


## *List comprehension* con condición `if`

Su sintaxis básica es: 

![listcondicion](https://github.com/Hack-io-Data/Imagenes/blob/main/02-Imagenes/Python_b%C3%A1sico/list_comprehension_condicion.png?raw=true)

Como hemos observado en el diagrama inicial, podemos agregar una condición adicional con un `if` en una *list comprehension*. En Python, una *list comprehension* con un `for` y un `if` es una forma concisa de crear una lista aplicando una condición a cada elemento. En términos simples, utilizamos un `for` para iterar sobre una secuencia de elementos y un `if` para aplicar una condición a cada elemento. Los elementos que cumplen con la condición se incluyen en la lista resultante. Regresemos al primer ejemplo que presentamos, el de elevar al cuadrado una lista de números. En este caso, solo deseamos elevar al cuadrado los números pares. Veamos cómo lograrlo:

In [27]:
%%time
# primero con un for normal
# creamos la lista vacía donde apendearemos los resultados 

cuadrados_pares = []
print("La lista con los cuadrados de los números contiene:", cuadrados_pares)
print("--------------------------------")
# iniciamos nuestro for
for num in range(50000000):

    # establecemos la condición para los números pares. Recordemos que el operador % nos devolvía el resto de una división. Si el resultado de este operador es 0, significa que el número es par, y por lo tanto, querremos calcular su cuadrado. 
    if num % 2 == 0: 

        # si se cumple la condición, eleveramos al cuadrado el número y lo apendearemos a la lista de cuadrados_pares. En esta lista solo tendremos números pares
        cuadrados_pares.append(num ** 2)
    # recordemos que el else no es obligatorio. Por lo tanto, no pondremos la condición else, ya que en caso de que no sea número par no querremos que pase nada.
    
print("La lista DESPUÉS DEL BUCLE FOR contiene, notad como solo hemos mostrado los primeros elementos para simplificar el output:", cuadrados_pares[:20]) 

La lista con los cuadrados de los números contiene: []
--------------------------------
La lista DESPUÉS DEL BUCLE FOR contiene, notad como solo hemos mostrado los primeros elementos para simplificar el output: [0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444]
CPU times: user 1.61 s, sys: 108 ms, total: 1.72 s
Wall time: 1.73 s


In [28]:
%%time
# con una list comprehension

cuadrados_pares2 = [num ** 2 for num in range(50000000) if num % 2 == 0]
print("La lista contiene, notad como solo hemos mostrado los primeros elementos para simplificar el output:", cuadrados_pares2[:20])

La lista contiene, notad como solo hemos mostrado los primeros elementos para simplificar el output: [0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444]
CPU times: user 1.11 s, sys: 101 ms, total: 1.21 s
Wall time: 1.23 s


<div style="background-color: #FFBB33; padding: 10px; border-left: 6px solid #000080; color: black; border-radius: 10px;">

<strong>Desglosemos ahora la *list comprehension* que acabamos de escribir.</strong>


Las primeras partes son iguales que en el primer ejemplo que presentamos:

- Hemos definido una variable llamada `cuadrado2` donde se guardarán los resultados del *for loop*. Es igual que en el primer ejemplo.

- Para crear una *list comprehension*, debemos indicar los corchetes `[]` al principio y al final. Es igual que en el primer ejemplo.

- Dentro de los corchetes, lo primero que hemos colocado es `num ** 2`, lo cual corresponde a lo que queremos agregar en nuestra lista nueva. Esta parte es equivalente a la segunda línea de nuestro *for* original. Indica qué queremos hacer con cada elemento de nuestra lista original. Es igual que en el primer ejemplo.

- Luego hemos añadido `for num in range(5000000)`, lo que significa que estamos iniciando nuestro *for loop*. Es igual que en el primer ejemplo.

- Por último, hemos agregado la condición `if num % 2 == 0`. Esta es la parte nueva, la condición que deseamos verificar.
</div>

## *List comprehension* con condición `if`... `else`

Pero... ¿Qué pasaría si quisieramos añadir una condición *elif* o *else* en nuestra *list comprehension*? 

- El *else* se puede incluir sin problema, ahora veremos un ejemplo

- El *elif*  no lo podremos incluir ya que las *list comprehensions* están diseñadas para ser cortas y sencillas. Si empezamos a incluir múltiples condiciones perdería su utilidad. 

Su sintaxis básica es: 

![sintaxis](https://github.com/Hack-io-Data/Imagenes/blob/main/02-Imagenes/Python_b%C3%A1sico/list_comprehension_condicion2.png?raw=true)

Veamos un ejemplo con *else*. Volvamos al ejemplo de la lista de palabras. En este caso, querremos que en la lista nueva se nos añada "palabra larga" o "palabra corta" en función de su longitud. De esta forma: 

- Palabras cuya longitud sea menor que 6 apendearemos "palabra corta"

- Palabras cuya longitud sea mayor que 6 apendearemos "palabra larga"

In [32]:
%%time
# veamos como hacerlo con un for loop normal
print("La lista 'palabras' contiene:", herramientas)
print("----------------------")

# definimos la lista vacía dnode apendearemos los resultados
palabras_clas = []

# iniciamos el for loop
for i in herramientas: 

    # establecemos la primera condición. Que la longitud de la palabra sea menor o igual que 6
    if len(i) <= 6:

        # apendeamos "palabra corta" a la lista vacía
        palabras_clas.append("palabra corta")

    # en caso de que no se cumpla esa condición
    else: 

        # apendearemos "palabra larga" a la lista vacía
        palabras_clas.append("palabra larga")
print("La lista 'palabras_class' contiene:", palabras_clas)

La lista 'palabras' contiene: ['Regresión Lineal', 'Power BI', 'Pandas', 'SQL']
----------------------
La lista 'palabras_class' contiene: ['palabra larga', 'palabra larga', 'palabra corta', 'palabra corta']
CPU times: user 72 µs, sys: 8 µs, total: 80 µs
Wall time: 76.8 µs


In [33]:
%%time
# como lo haríamos con una list comprehension?

palabras_clas2 = ["palabra corta" if len(i) <= 6 else "palabra larga" for i in palabras  ]
print("La lista 'palabras_class2' contiene:", palabras_clas2)

La lista 'palabras_class2' contiene: ['palabra corta', 'palabra corta', 'palabra larga', 'palabra corta', 'palabra larga']
CPU times: user 62 µs, sys: 6 µs, total: 68 µs
Wall time: 67.2 µs


<div style="background-color: #F74646; padding: 10px; border-left: 6px solid #000080; color: black; border-radius: 10px;">

**Evaluemos ahora el código anterior:**

La sintaxis ha evolucionado un poco y se ha vuelto más compleja. Sin embargo, desglosemos cada parte para comprenderla mejor:

- En primer lugar, tenemos `"palabra corta"`. Esto indica lo que se agregará a la lista si se cumple la condición especificada en el `if`.

- Luego, encontramos el `if len(i) <= 6`, que representa la primera condición que queremos verificar.

- A continuación, aparece el `else "palabra larga"`, que determina qué se agregará a la lista si la condición establecida previamente no se cumple.

- Por último, tenemos el `for i in palabras`, que marca el inicio del bucle `for`.
</div>


## *Nested List Comprehension*

Puede parecer un poco abrumador al principio, pero no os preocupeis. Nuestra recomendación es que, en estos primeros pasos, siempre escribáis el bucle `for` de la forma tradicional y luego intentéis convertirlo en una *list comprehension* como hemos hecho en cada uno de los ejemplos anteriores.

Su sintaxis básica es: 

![sintaxis](https://github.com/Hack-io-Data/Imagenes/blob/main/02-Imagenes/Python_b%C3%A1sico/list_comprehension_condicion2.png?raw=true)



Ya hemos visto que es es posible utilizar una *list comprehension* con dos bucles `for`. Una vez más, veámoslo con un ejemplo. Supongamos que tenemos una lista de listas de números y queremos convertirla en una única lista. 

In [35]:
%%time 

# lo primero que hacemos es definir una lista de listas
listas = [[11,12,13], [14,15,16], [17,18,19]]
print("La lista de listas contiene:", listas)
print("----------------------------------")


# para hacer de esta lista de listas una única lista tendremos que hacer dos for loop. Lo haremos paso a paso. 
# primero definimos la lista vacía donde iremos añadiendo los números de nuestra lista de listas
lista_aplanada = []
print("La lista donde almacenaremos los resultados contiene:", lista_aplanada)
print("----------------------------------")


# iniciamos el for loop
for sublista in listas : 

    # nuestro primero elemento interable será cada una de las listas de la lista grande. Esto, todavía no nos esta permitiendo acceder a cada uno de los números, por lo que tenemos que volver a iterar por cada una de las sublistas
    print(sublista)
    print("...................")

    # iteramos por cada sublista para acceder a cada uno de los números.
    for num in sublista:

        # ahora num será cada elemento de cada sublista, es decir, cada número.  
        print(num)
        print("...................")


        # es en este punto, donde ya hemos accedido a cada número donde lo apendearemos a la lista vacía

        lista_aplanada.append(num)
 
print("La lista donde almacenaremos los resultados DESPUÉS DE LOS DOS FOR LOOP contiene:", lista_aplanada)
       


La lista de listas contiene: [[11, 12, 13], [14, 15, 16], [17, 18, 19]]
----------------------------------
La lista donde almacenaremos los resultados contiene: []
----------------------------------
[11, 12, 13]
...................
11
...................
12
...................
13
...................
[14, 15, 16]
...................
14
...................
15
...................
16
...................
[17, 18, 19]
...................
17
...................
18
...................
19
...................
La lista donde almacenaremos los resultados DESPUÉS DE LOS DOS FOR LOOP contiene: [11, 12, 13, 14, 15, 16, 17, 18, 19]
CPU times: user 102 µs, sys: 5 µs, total: 107 µs
Wall time: 105 µs


In [36]:
%%time
# ¿Cómo haremos esto con una list comprehension? 
lista_aplanada2 = [num for sublista in listas for num in sublista]
print("La lista donde almacenaremos los resultados DESPUÉS DE LA LIST COMPREHENSION contiene:", lista_aplanada2)


La lista donde almacenaremos los resultados DESPUÉS DE LA LIST COMPREHENSION contiene: [11, 12, 13, 14, 15, 16, 17, 18, 19]
CPU times: user 61 µs, sys: 6 µs, total: 67 µs
Wall time: 63.9 µs


<div style="background-color: #FFBB33; padding: 10px; border-left: 6px solid #000080; color: black; border-radius: 10px;">

**Analicemos detenidamente lo que sucede aquí:**

- `num` es el elemento que queremos añadir a nuestra nueva lista.

- Luego, tenemos el primer bucle `for`, `for sublista in listas`, que itera sobre cada sublista en nuestra lista de listas.

- Finalmente, tenemos el segundo bucle `for`, `for num in sublista`, que itera sobre cada número dentro de cada sublista en nuestra lista de listas.
</div>